In [2]:
import pandas as pd
import os
import numpy as np
from pathlib import Path

In [3]:
df = pd.read_csv("../data/raw/Tingkat Penghunian Kamar Hotel, 2025.csv")
df.head()

,Jenis Hotel,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Tingkat Penghunian Kamar Hotel (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,1.a. Hotel Bintang 1,29.15,30.15,17.32,29.85,27.46,26.59,28.79,23.71,23.96,25.73,27.66,29.65,-
4,1.b. Hotel Bintang 2,45.83,42.94,30.08,48.15,49.59,46.4,45.23,45.44,43.89,46.98,48.52,52.49,-

In [4]:
print(df.shape)

df.info()

df.head(10)

(15, 14)
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Jenis Hotel  12 non-null     str
 1   Unnamed: 1   15 non-null     str
 2   Unnamed: 2   13 non-null     str
 3   Unnamed: 3   13 non-null     str
 4   Unnamed: 4   13 non-null     str
 5   Unnamed: 5   13 non-null     str
 6   Unnamed: 6   13 non-null     str
 7   Unnamed: 7   13 non-null     str
 8   Unnamed: 8   13 non-null     str
 9   Unnamed: 9   13 non-null     str
 10  Unnamed: 10  13 non-null     str
 11  Unnamed: 11  13 non-null     str
 12  Unnamed: 12  13 non-null     str
 13  Unnamed: 13  13 non-null     str
dtypes: str(14)
memory usage: 2.9 KB

,Jenis Hotel,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Tingkat Penghunian Kamar Hotel (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,1.a. Hotel Bintang 1,29.15,30.15,17.32,29.85,27.46,26.59,28.79,23.71,23.96,25.73,27.66,29.65,-
4,1.b. Hotel Bintang 2,45.83,42.94,30.08,48.15,49.59,46.4,45.23,45.44,43.89,46.98,48.52,52.49,-
5,1.c. Hotel Bintang 3,43.33,41.22,26.75,43.38,42.88,44.12,45.6,41.75,41.97,45.13,48.44,52.99,-
6,1.d. Hotel Bintang 4,52.08,50.53,30.92,49.98,52.62,51.2,55.82,50.61,51.3,58.1,61.6,65.96,-
7,1.e. Hotel Bintang 5,58.79,54.18,32.58,50.23,48.65,54.27,56.97,54.51,51.78,56.81,62.3,69.47,-
8,1. Hotel Berbintang Total,47.59,45.51,28.77,46.37,47.08,47.08,49.52,45.75,45.66,50.24,53.54,58.13,-
9,2.a. Hotel NonBintang; kamar <10,17.01,14.3,7.99,23.43,19.78,19.12,17.63,17.43,15.76,15.3,17.35,23.69,-

In [5]:
df.isna().sum()
print('----')
df.duplicated().sum()
print('----')
df.describe()

----
----

,Jenis Hotel,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,12,15,13,13,13,13,13,13,13,13,13,13,13,13
unique,12,15,13,13,13,13,12,13,13,13,13,13,13,2
top,1.a. Hotel Bintang 1,Tingkat Penghunian Kamar Hotel (Persen),Februari,Maret,April,Mei,23.14,Juli,Agustus,September,Oktober,November,Desember,-
freq,1,1,1,1,1,1,2,1,1,1,1,1,1,12

In [6]:
hotel = pd.read_csv(
    "../data/raw/Tingkat Penghunian Kamar Hotel, 2025.csv"
)

hotel.columns = [
    "jenis_hotel",
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
    "annual"
]

hotel = hotel.iloc[3:].reset_index(drop=True)

In [7]:
hotel.head(15)

,jenis_hotel,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual
0,1.a. Hotel Bintang 1,29.15,30.15,17.32,29.85,27.46,26.59,28.79,23.71,23.96,25.73,27.66,29.65,-
1,1.b. Hotel Bintang 2,45.83,42.94,30.08,48.15,49.59,46.4,45.23,45.44,43.89,46.98,48.52,52.49,-
2,1.c. Hotel Bintang 3,43.33,41.22,26.75,43.38,42.88,44.12,45.6,41.75,41.97,45.13,48.44,52.99,-
3,1.d. Hotel Bintang 4,52.08,50.53,30.92,49.98,52.62,51.2,55.82,50.61,51.3,58.1,61.6,65.96,-
4,1.e. Hotel Bintang 5,58.79,54.18,32.58,50.23,48.65,54.27,56.97,54.51,51.78,56.81,62.3,69.47,-
5,1. Hotel Berbintang Total,47.59,45.51,28.77,46.37,47.08,47.08,49.52,45.75,45.66,50.24,53.54,58.13,-
6,2.a. Hotel NonBintang; kamar <10,17.01,14.3,7.99,23.43,19.78,19.12,17.63,17.43,15.76,15.3,17.35,23.69,-
7,2.b. Hotel NonBintang; kamar 10-24,23.07,20.7,13.36,26.27,22.53,23.14,22.39,21,22.46,21.78,22.85,27.27,-
8,2.c. Hotel NonBintang; kamar 25-40,27.22,24.32,17.79,27.26,25.8,25.56,24.73,24.64,25.29,25.57,27,29.84,-
9,2.d. Hotel NonBintang; kamar >40,22.79,20.86,13.64,25.01,24.05,22.9,23.52,22.13,22.93,23.18,24.04,27.57,-
10,2. Hotel NonBintang Total,23.72,21.33,14.37,25.76,23.42,23.14,22.68,21.76,22.43,22.26,23.48,27.51,-
11,3. Hotel Berbintang dan NonBintang Total,40.08,37.88,24.28,38.07,37.59,37.5,38.8,36.12,36.33,38.9,41.41,45.75,-

In [8]:
hotel.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   jenis_hotel  12 non-null     str
 1   jan          12 non-null     str
 2   feb          12 non-null     str
 3   mar          12 non-null     str
 4   apr          12 non-null     str
 5   may          12 non-null     str
 6   jun          12 non-null     str
 7   jul          12 non-null     str
 8   aug          12 non-null     str
 9   sep          12 non-null     str
 10  oct          12 non-null     str
 11  nov          12 non-null     str
 12  dec          12 non-null     str
 13  annual       12 non-null     str
dtypes: str(14)
memory usage: 2.5 KB

In [9]:
display(hotel)

,jenis_hotel,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual
0,1.a. Hotel Bintang 1,29.15,30.15,17.32,29.85,27.46,26.59,28.79,23.71,23.96,25.73,27.66,29.65,-
1,1.b. Hotel Bintang 2,45.83,42.94,30.08,48.15,49.59,46.4,45.23,45.44,43.89,46.98,48.52,52.49,-
2,1.c. Hotel Bintang 3,43.33,41.22,26.75,43.38,42.88,44.12,45.6,41.75,41.97,45.13,48.44,52.99,-
3,1.d. Hotel Bintang 4,52.08,50.53,30.92,49.98,52.62,51.2,55.82,50.61,51.3,58.1,61.6,65.96,-
4,1.e. Hotel Bintang 5,58.79,54.18,32.58,50.23,48.65,54.27,56.97,54.51,51.78,56.81,62.3,69.47,-
5,1. Hotel Berbintang Total,47.59,45.51,28.77,46.37,47.08,47.08,49.52,45.75,45.66,50.24,53.54,58.13,-
6,2.a. Hotel NonBintang; kamar <10,17.01,14.3,7.99,23.43,19.78,19.12,17.63,17.43,15.76,15.3,17.35,23.69,-
7,2.b. Hotel NonBintang; kamar 10-24,23.07,20.7,13.36,26.27,22.53,23.14,22.39,21,22.46,21.78,22.85,27.27,-
8,2.c. Hotel NonBintang; kamar 25-40,27.22,24.32,17.79,27.26,25.8,25.56,24.73,24.64,25.29,25.57,27,29.84,-
9,2.d. Hotel NonBintang; kamar >40,22.79,20.86,13.64,25.01,24.05,22.9,23.52,22.13,22.93,23.18,24.04,27.57,-
10,2. Hotel NonBintang Total,23.72,21.33,14.37,25.76,23.42,23.14,22.68,21.76,22.43,22.26,23.48,27.51,-
11,3. Hotel Berbintang dan NonBintang Total,40.08,37.88,24.28,38.07,37.59,37.5,38.8,36.12,36.33,38.9,41.41,45.75,-

In [10]:
hotel["annual"].value_counts(dropna=False)

annual
-    12
Name: count, dtype: int64

In [11]:
hotel = hotel.drop(columns=["annual"])

In [12]:
month_cols = [
    "jan","feb","mar","apr","may","jun",
    "jul","aug","sep","oct","nov","dec"
]

hotel[month_cols] = hotel[month_cols].astype(float)

In [13]:
hotel.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   jenis_hotel  12 non-null     str
 1   jan          12 non-null     float64
 2   feb          12 non-null     float64
 3   mar          12 non-null     float64
 4   apr          12 non-null     float64
 5   may          12 non-null     float64
 6   jun          12 non-null     float64
 7   jul          12 non-null     float64
 8   aug          12 non-null     float64
 9   sep          12 non-null     float64
 10  oct          12 non-null     float64
 11  nov          12 non-null     float64
 12  dec          12 non-null     float64
dtypes: float64(12), str(1)
memory usage: 1.7 KB

In [14]:
hotel["jenis_hotel"].tolist()

['1.a. Hotel Bintang 1',
 '1.b. Hotel Bintang 2',
 '1.c. Hotel Bintang 3',
 '1.d. Hotel Bintang 4',
 '1.e. Hotel Bintang 5',
 '1. Hotel Berbintang Total',
 '2.a. Hotel NonBintang; kamar <10',
 '2.b. Hotel NonBintang; kamar 10-24',
 '2.c. Hotel NonBintang; kamar 25-40',
 '2.d. Hotel NonBintang; kamar >40',
 '2. Hotel NonBintang Total',
 '3. Hotel Berbintang dan NonBintang Total']

Preprocessing Function

In [15]:
import pandas as pd
import re

def preprocess_hotel(filepath):
    
    # Ambil tahun dari nama file
    year = int(re.search(r'(\d{4})', str(filepath)).group(1))

    # Load data
    df = pd.read_csv(filepath)

    # Rename kolom
    df.columns = [
        "jenis_hotel",
        "jan",
        "feb",
        "mar",
        "apr",
        "may",
        "jun",
        "jul",
        "aug",
        "sep",
        "oct",
        "nov",
        "dec",
        "annual"
    ]

    # Buang header tambahan
    df = df.iloc[3:].reset_index(drop=True)

    # Drop annual
    df = df.drop(columns=["annual"])

    # Convert numerik
    month_cols = [
        "jan","feb","mar","apr","may","jun",
        "jul","aug","sep","oct","nov","dec"
    ]

    df[month_cols] = (
    df[month_cols]
    .replace("-", np.nan)
    .astype(float)
)

    # Tambah tahun
    df["tahun"] = year

    return df

In [16]:
hotel_2025 = preprocess_hotel(
    "../data/raw/Tingkat Penghunian Kamar Hotel, 2025.csv"
)

display(hotel_2025.head())

hotel_2025.info()

,jenis_hotel,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,tahun
0,1.a. Hotel Bintang 1,29.15,30.15,17.32,29.85,27.46,26.59,28.79,23.71,23.96,25.73,27.66,29.65,2025
1,1.b. Hotel Bintang 2,45.83,42.94,30.08,48.15,49.59,46.40,45.23,45.44,43.89,46.98,48.52,52.49,2025
2,1.c. Hotel Bintang 3,43.33,41.22,26.75,43.38,42.88,44.12,45.60,41.75,41.97,45.13,48.44,52.99,2025
3,1.d. Hotel Bintang 4,52.08,50.53,30.92,49.98,52.62,51.20,55.82,50.61,51.30,58.10,61.60,65.96,2025
4,1.e. Hotel Bintang 5,58.79,54.18,32.58,50.23,48.65,54.27,56.97,54.51,51.78,56.81,62.30,69.47,2025

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   jenis_hotel  12 non-null     str
 1   jan          12 non-null     float64
 2   feb          12 non-null     float64
 3   mar          12 non-null     float64
 4   apr          12 non-null     float64
 5   may          12 non-null     float64
 6   jun          12 non-null     float64
 7   jul          12 non-null     float64
 8   aug          12 non-null     float64
 9   sep          12 non-null     float64
 10  oct          12 non-null     float64
 11  nov          12 non-null     float64
 12  dec          12 non-null     float64
 13  tahun        12 non-null     int64
dtypes: float64(12), int64(1), str(1)
memory usage: 1.8 KB

In [17]:
from pathlib import Path

hotel_files = sorted(
    Path("../data/raw").glob(
        "Tingkat Penghunian Kamar Hotel, *.csv"
    )
)

hotel_files

[PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2019.csv'),
 PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2020.csv'),
 PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2021.csv'),
 PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2022.csv'),
 PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2023.csv'),
 PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2024.csv'),
 PosixPath('../data/raw/Tingkat Penghunian Kamar Hotel, 2025.csv')]

In [18]:
# Cell 4 (debug)

for file in hotel_files:
    try:
        df = preprocess_hotel(file)
        print(f"SUCCESS: {file.name}")

    except Exception as e:
        print(f"ERROR: {file.name}")
        print(e)
        break

SUCCESS: Tingkat Penghunian Kamar Hotel, 2019.csv
SUCCESS: Tingkat Penghunian Kamar Hotel, 2020.csv
SUCCESS: Tingkat Penghunian Kamar Hotel, 2021.csv
SUCCESS: Tingkat Penghunian Kamar Hotel, 2022.csv
SUCCESS: Tingkat Penghunian Kamar Hotel, 2023.csv
SUCCESS: Tingkat Penghunian Kamar Hotel, 2024.csv
SUCCESS: Tingkat Penghunian Kamar Hotel, 2025.csv

In [19]:
all_hotels = []

for file in hotel_files:

    df = preprocess_hotel(file)

    all_hotels.append(df)

hotel_wide = pd.concat(
    all_hotels,
    ignore_index=True
)

print(hotel_wide.shape)

display(hotel_wide.head())

display(hotel_wide.tail())

(84, 14)

,jenis_hotel,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,tahun
0,1.a. Hotel Bintang 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,1.b. Hotel Bintang 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
2,1.c. Hotel Bintang 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
3,1.d. Hotel Bintang 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
4,1.e. Hotel Bintang 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019

,jenis_hotel,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,tahun
79,2.b. Hotel NonBintang; kamar 10-24,23.07,20.70,13.36,26.27,22.53,23.14,22.39,21.00,22.46,21.78,22.85,27.27,2025
80,2.c. Hotel NonBintang; kamar 25-40,27.22,24.32,17.79,27.26,25.80,25.56,24.73,24.64,25.29,25.57,27.00,29.84,2025
81,2.d. Hotel NonBintang; kamar >40,22.79,20.86,13.64,25.01,24.05,22.90,23.52,22.13,22.93,23.18,24.04,27.57,2025
82,2. Hotel NonBintang Total,23.72,21.33,14.37,25.76,23.42,23.14,22.68,21.76,22.43,22.26,23.48,27.51,2025
83,3. Hotel Berbintang dan NonBintang Total,40.08,37.88,24.28,38.07,37.59,37.50,38.80,36.12,36.33,38.90,41.41,45.75,2025

# Data Transformation

In [20]:
hotel_long = pd.melt(
    hotel_wide,
    id_vars=["tahun", "jenis_hotel"],
    value_vars=[
        "jan","feb","mar","apr","may","jun",
        "jul","aug","sep","oct","nov","dec"
    ],
    var_name="bulan",
    value_name="tpk"
)

hotel_long.head()

   tahun           jenis_hotel bulan  tpk
0   2019  1.a. Hotel Bintang 1   jan  NaN
1   2019  1.b. Hotel Bintang 2   jan  NaN
2   2019  1.c. Hotel Bintang 3   jan  NaN
3   2019  1.d. Hotel Bintang 4   jan  NaN
4   2019  1.e. Hotel Bintang 5   jan  NaN

In [21]:
print(hotel_long.shape)

display(hotel_long.head(20))

hotel_long.info()

(1008, 4)

    tahun                               jenis_hotel bulan    tpk
0    2019                      1.a. Hotel Bintang 1   jan    NaN
1    2019                      1.b. Hotel Bintang 2   jan    NaN
2    2019                      1.c. Hotel Bintang 3   jan    NaN
3    2019                      1.d. Hotel Bintang 4   jan    NaN
4    2019                      1.e. Hotel Bintang 5   jan    NaN
5    2019                 1. Hotel Berbintang Total   jan  54.33
6    2019          2.a. Hotel NonBintang; kamar <10   jan    NaN
7    2019        2.b. Hotel NonBintang; kamar 10-24   jan    NaN
8    2019        2.c. Hotel NonBintang; kamar 25-40   jan    NaN
9    2019          2.d. Hotel NonBintang; kamar >40   jan    NaN
10   2019                 2. Hotel NonBintang Total   jan  36.72
11   2019  3. Hotel Berbintang dan NonBintang Total   jan  51.45
12   2020                      1.a. Hotel Bintang 1   jan    NaN
13   2020                      1.b. Hotel Bintang 2   jan    NaN
14   2020                      1.c. Hotel Bintang 3   jan    NaN
15   2020                      1.d. Hotel Bintang 4   jan    NaN
16   2020                      1.e. Hotel Bintang 5   jan    NaN
17   2020                 1. Hotel Berbintang Total   jan  47.06
18   2020          2.a. Hotel NonBintang; kamar <10   jan    NaN
19   2020        2.b. Hotel NonBintang; kamar 10-24   jan    NaN

<class 'pandas.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tahun        1008 non-null   int64
 1   jenis_hotel  1008 non-null   str
 2   bulan        1008 non-null   str
 3   tpk          432 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 61.3 KB

In [22]:
hotel_long.isnull().sum()

tahun            0
jenis_hotel      0
bulan            0
tpk            576
dtype: int64

In [23]:
hotel_long.groupby("tahun").size()

tahun
2019    144
2020    144
2021    144
2022    144
2023    144
2024    144
2025    144
dtype: int64

In [24]:
hotel_long.head()

   tahun           jenis_hotel bulan  tpk
0   2019  1.a. Hotel Bintang 1   jan  NaN
1   2019  1.b. Hotel Bintang 2   jan  NaN
2   2019  1.c. Hotel Bintang 3   jan  NaN
3   2019  1.d. Hotel Bintang 4   jan  NaN
4   2019  1.e. Hotel Bintang 5   jan  NaN

In [25]:
print(hotel_long.shape)

(1008, 4)

In [26]:
hotel_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tahun        1008 non-null   int64
 1   jenis_hotel  1008 non-null   str
 2   bulan        1008 non-null   str
 3   tpk          432 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 61.3 KB

In [27]:
hotel_long.groupby("tahun")["tpk"].count()

tahun
2019     36
2020     36
2021     36
2022     24
2023     12
2024    144
2025    144
Name: tpk, dtype: int64

In [28]:
hotel_long.groupby("jenis_hotel")["tpk"].count()

jenis_hotel
1. Hotel Berbintang Total                   76
1.a. Hotel Bintang 1                        24
1.b. Hotel Bintang 2                        24
1.c. Hotel Bintang 3                        24
1.d. Hotel Bintang 4                        24
1.e. Hotel Bintang 5                        24
2. Hotel NonBintang Total                   76
2.a. Hotel NonBintang; kamar <10            24
2.b. Hotel NonBintang; kamar 10-24          24
2.c. Hotel NonBintang; kamar 25-40          24
2.d. Hotel NonBintang; kamar >40            24
3. Hotel Berbintang dan NonBintang Total    64
Name: tpk, dtype: int64

In [29]:
bulan_map = {
    "jan": "Januari",
    "feb": "Februari",
    "mar": "Maret",
    "apr": "April",
    "may": "Mei",
    "jun": "Juni",
    "jul": "Juli",
    "aug": "Agustus",
    "sep": "September",
    "oct": "Oktober",
    "nov": "November",
    "dec": "Desember"
}

hotel_long["bulan"] = hotel_long["bulan"].map(bulan_map)

In [30]:
hotel_long.head()

   tahun           jenis_hotel    bulan  tpk
0   2019  1.a. Hotel Bintang 1  Januari  NaN
1   2019  1.b. Hotel Bintang 2  Januari  NaN
2   2019  1.c. Hotel Bintang 3  Januari  NaN
3   2019  1.d. Hotel Bintang 4  Januari  NaN
4   2019  1.e. Hotel Bintang 5  Januari  NaN

In [31]:
hotel_long['bulan'].value_counts()

bulan
Januari      84
Februari     84
Maret        84
April        84
Mei          84
Juni         84
Juli         84
Agustus      84
September    84
Oktober      84
November     84
Desember     84
Name: count, dtype: int64

In [32]:
hotel_long = hotel_long[
    [
        "tahun",
        "bulan",
        "jenis_hotel",
        "tpk"
    ]
]

In [33]:
hotel_long.to_csv(
    "../data/processed/hotel_clean.csv",
    index=False
)

# Checking

In [34]:
hotel_long.head()

   tahun    bulan           jenis_hotel  tpk
0   2019  Januari  1.a. Hotel Bintang 1  NaN
1   2019  Januari  1.b. Hotel Bintang 2  NaN
2   2019  Januari  1.c. Hotel Bintang 3  NaN
3   2019  Januari  1.d. Hotel Bintang 4  NaN
4   2019  Januari  1.e. Hotel Bintang 5  NaN

In [35]:
hotel_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tahun        1008 non-null   int64
 1   bulan        1008 non-null   str
 2   jenis_hotel  1008 non-null   str
 3   tpk          432 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 64.5 KB

In [36]:
hotel_long[hotel_long['tahun'] == 2025]

      tahun     bulan                               jenis_hotel    tpk
72     2025   Januari                      1.a. Hotel Bintang 1  29.15
73     2025   Januari                      1.b. Hotel Bintang 2  45.83
74     2025   Januari                      1.c. Hotel Bintang 3  43.33
75     2025   Januari                      1.d. Hotel Bintang 4  52.08
76     2025   Januari                      1.e. Hotel Bintang 5  58.79
...     ...       ...                                       ...    ...
1003   2025  Desember        2.b. Hotel NonBintang; kamar 10-24  27.27
1004   2025  Desember        2.c. Hotel NonBintang; kamar 25-40  29.84
1005   2025  Desember          2.d. Hotel NonBintang; kamar >40  27.57
1006   2025  Desember                 2. Hotel NonBintang Total  27.51
1007   2025  Desember  3. Hotel Berbintang dan NonBintang Total  45.75

[144 rows x 4 columns]

In [37]:
hotel_long['jenis_hotel'].value_counts()

jenis_hotel
1.a. Hotel Bintang 1                        84
1.b. Hotel Bintang 2                        84
1.c. Hotel Bintang 3                        84
1.d. Hotel Bintang 4                        84
1.e. Hotel Bintang 5                        84
1. Hotel Berbintang Total                   84
2.a. Hotel NonBintang; kamar <10            84
2.b. Hotel NonBintang; kamar 10-24          84
2.c. Hotel NonBintang; kamar 25-40          84
2.d. Hotel NonBintang; kamar >40            84
2. Hotel NonBintang Total                   84
3. Hotel Berbintang dan NonBintang Total    84
Name: count, dtype: int64

In [40]:
hotel_long[(hotel_long['tahun'] == 2022)]

     tahun     bulan                               jenis_hotel    tpk
36    2022   Januari                      1.a. Hotel Bintang 1    NaN
37    2022   Januari                      1.b. Hotel Bintang 2    NaN
38    2022   Januari                      1.c. Hotel Bintang 3    NaN
39    2022   Januari                      1.d. Hotel Bintang 4    NaN
40    2022   Januari                      1.e. Hotel Bintang 5    NaN
..     ...       ...                                       ...    ...
967   2022  Desember        2.b. Hotel NonBintang; kamar 10-24    NaN
968   2022  Desember        2.c. Hotel NonBintang; kamar 25-40    NaN
969   2022  Desember          2.d. Hotel NonBintang; kamar >40    NaN
970   2022  Desember                 2. Hotel NonBintang Total  25.97
971   2022  Desember  3. Hotel Berbintang dan NonBintang Total    NaN

[144 rows x 4 columns]

In [47]:
hotel_long.loc[
    hotel_long["tahun"] == 2022,
    "bulan"
].unique()

<ArrowStringArray>
[  'Januari',  'Februari',     'Maret',     'April',       'Mei',      'Juni',
      'Juli',   'Agustus', 'September',   'Oktober',  'November',  'Desember']
Length: 12, dtype: str

In [48]:
hotel_long.loc[
    hotel_long["tahun"] == 2023,
    "bulan"
].unique()

<ArrowStringArray>
[  'Januari',  'Februari',     'Maret',     'April',       'Mei',      'Juni',
      'Juli',   'Agustus', 'September',   'Oktober',  'November',  'Desember']
Length: 12, dtype: str

In [45]:
hotel_long.loc[
    hotel_long["tahun"] == 2022
].groupby("bulan").size()

bulan
Agustus      12
April        12
Desember     12
Februari     12
Januari      12
Juli         12
Juni         12
Maret        12
Mei          12
November     12
Oktober      12
September    12
dtype: int64