In [2]:
import pandas as pd
import os
import numpy as np
from pathlib import Path

In [3]:
df = pd.read_csv("../data/raw/jumlah_objek_wisata.csv")

In [6]:
df

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jenis_odtw,jumlah_odtw,satuan,tahun
0,1,32,JAWA BARAT,3201,KABUPATEN BOGOR,ALAM,38,LOKASI,2014
1,2,32,JAWA BARAT,3201,KABUPATEN BOGOR,BUDAYA,3,LOKASI,2014
2,3,32,JAWA BARAT,3201,KABUPATEN BOGOR,MINAT KHUSUS,4,LOKASI,2014
3,4,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,ALAM,36,LOKASI,2014
4,5,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,BUDAYA,7,LOKASI,2014
...,...,...,...,...,...,...,...,...,...
883,884,32,JAWA BARAT,3278,KOTA TASIKMALAYA,BUDAYA,26,LOKASI,2024
884,885,32,JAWA BARAT,3278,KOTA TASIKMALAYA,BUATAN,11,LOKASI,2024
885,886,32,JAWA BARAT,3279,KOTA BANJAR,ALAM,9,LOKASI,2024
886,887,32,JAWA BARAT,3279,KOTA BANJAR,BUDAYA,3,LOKASI,2024
887,888,32,JAWA BARAT,3279,KOTA BANJAR,BUATAN,12,LOKASI,2024

# Quality Check

In [10]:
print(df.shape)

df.info()

df.describe(include="all")

(888, 9)
<class 'pandas.DataFrame'>
RangeIndex: 888 entries, 0 to 887
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   888 non-null    int64
 1   kode_provinsi        888 non-null    int64
 2   nama_provinsi        888 non-null    str
 3   kode_kabupaten_kota  888 non-null    int64
 4   nama_kabupaten_kota  888 non-null    str
 5   jenis_odtw           888 non-null    str
 6   jumlah_odtw          888 non-null    int64
 7   satuan               888 non-null    str
 8   tahun                888 non-null    int64
dtypes: int64(5), str(4)
memory usage: 95.5 KB

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jenis_odtw,jumlah_odtw,satuan,tahun
count,888.000000,888.0,888,888.000000,888,888,888.000000,888,888.000000
unique,NaN,NaN,1,NaN,27,4,NaN,1,NaN
top,NaN,NaN,JAWA BARAT,NaN,KABUPATEN BOGOR,ALAM,NaN,LOKASI,NaN
freq,NaN,NaN,888,NaN,33,296,NaN,888,NaN
mean,444.500000,32.0,NaN,3231.378378,NaN,NaN,24.489865,NaN,2019.016892
std,256.487816,0.0,NaN,31.262479,NaN,NaN,38.255032,NaN,3.155987
min,1.000000,32.0,NaN,3201.000000,NaN,NaN,0.000000,NaN,2014.000000
25%,222.750000,32.0,NaN,3207.000000,NaN,NaN,3.000000,NaN,2016.000000
50%,444.500000,32.0,NaN,3214.000000,NaN,NaN,9.000000,NaN,2019.000000
75%,666.250000,32.0,NaN,3273.000000,NaN,NaN,30.000000,NaN,2022.000000
max,888.000000,32.0,NaN,3279.000000,NaN,NaN,386.000000,NaN,2024.000000

In [11]:
df.isnull().sum()

id                     0
kode_provinsi          0
nama_provinsi          0
kode_kabupaten_kota    0
nama_kabupaten_kota    0
jenis_odtw             0
jumlah_odtw            0
satuan                 0
tahun                  0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["jenis_odtw"].value_counts()

jenis_odtw
ALAM            296
BUDAYA          296
BUATAN          189
MINAT KHUSUS    107
Name: count, dtype: int64

In [14]:
sorted(df["tahun"].unique())

[np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024)]

In [15]:
df.info()

df.isnull().sum()

df.duplicated().sum()

df["jenis_odtw"].value_counts()

sorted(df["tahun"].unique())

df.groupby("tahun").size()

<class 'pandas.DataFrame'>
RangeIndex: 888 entries, 0 to 887
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   888 non-null    int64
 1   kode_provinsi        888 non-null    int64
 2   nama_provinsi        888 non-null    str
 3   kode_kabupaten_kota  888 non-null    int64
 4   nama_kabupaten_kota  888 non-null    str
 5   jenis_odtw           888 non-null    str
 6   jumlah_odtw          888 non-null    int64
 7   satuan               888 non-null    str
 8   tahun                888 non-null    int64
dtypes: int64(5), str(4)
memory usage: 95.5 KB

tahun
2014    78
2015    81
2016    81
2017    81
2018    81
2019    81
2020    81
2021    81
2022    81
2023    81
2024    81
dtype: int64

In [16]:
df.groupby("tahun").size()

tahun
2014    78
2015    81
2016    81
2017    81
2018    81
2019    81
2020    81
2021    81
2022    81
2023    81
2024    81
dtype: int64

In [17]:
df.groupby(["tahun", "jenis_odtw"]).size()

tahun  jenis_odtw
2014   ALAM            26
       BUDAYA          26
       MINAT KHUSUS    26
2015   ALAM            27
       BUDAYA          27
       MINAT KHUSUS    27
2016   ALAM            27
       BUDAYA          27
       MINAT KHUSUS    27
2017   ALAM            27
       BUDAYA          27
       MINAT KHUSUS    27
2018   ALAM            27
       BUATAN          27
       BUDAYA          27
2019   ALAM            27
       BUATAN          27
       BUDAYA          27
2020   ALAM            27
       BUATAN          27
       BUDAYA          27
2021   ALAM            27
       BUATAN          27
       BUDAYA          27
2022   ALAM            27
       BUATAN          27
       BUDAYA          27
2023   ALAM            27
       BUATAN          27
       BUDAYA          27
2024   ALAM            27
       BUATAN          27
       BUDAYA          27
dtype: int64

In [18]:
odtw_clean = df.drop(
    columns=[
        "id",
        "kode_provinsi",
        "nama_provinsi",
        "satuan"
    ]
)

In [19]:
odtw_clean = odtw_clean.rename(
    columns={
        "kode_kabupaten_kota": "kode_wilayah",
        "nama_kabupaten_kota": "kabupaten_kota",
        "jenis_odtw": "kategori_wisata",
        "jumlah_odtw": "jumlah_objek_wisata"
    }
)

In [20]:
odtw_clean = odtw_clean[
    [
        "tahun",
        "kode_wilayah",
        "kabupaten_kota",
        "kategori_wisata",
        "jumlah_objek_wisata"
    ]
]

In [21]:
odtw_clean.info()
odtw_clean.head()

<class 'pandas.DataFrame'>
RangeIndex: 888 entries, 0 to 887
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tahun                888 non-null    int64
 1   kode_wilayah         888 non-null    int64
 2   kabupaten_kota       888 non-null    str
 3   kategori_wisata      888 non-null    str
 4   jumlah_objek_wisata  888 non-null    int64
dtypes: int64(3), str(2)
memory usage: 53.9 KB

,tahun,kode_wilayah,kabupaten_kota,kategori_wisata,jumlah_objek_wisata
0,2014,3201,KABUPATEN BOGOR,ALAM,38
1,2014,3201,KABUPATEN BOGOR,BUDAYA,3
2,2014,3201,KABUPATEN BOGOR,MINAT KHUSUS,4
3,2014,3202,KABUPATEN SUKABUMI,ALAM,36
4,2014,3202,KABUPATEN SUKABUMI,BUDAYA,7

In [22]:
print("Jumlah Baris :", len(odtw_clean))
print("Jumlah Tahun :", odtw_clean["tahun"].nunique())
print("Jumlah Wilayah :", odtw_clean["kabupaten_kota"].nunique())
print("Kategori Wisata :")
print(sorted(odtw_clean["kategori_wisata"].unique()))

Jumlah Baris : 888
Jumlah Tahun : 11
Jumlah Wilayah : 27
Kategori Wisata :
['ALAM', 'BUATAN', 'BUDAYA', 'MINAT KHUSUS']

In [23]:
odtw_clean.to_csv(
    "../data/processed/odtw_clean.csv",
    index=False
)